repos:
  - repo: local
    hooks:
      - id: sync-shared
        name: Sync shared cookiecutter assets
        entry: bash -c 'poetry run python _scripts/sync_shared.py | grep "^\[modified\]" | cut -d] -f2- | xargs git add'
        language: system
        types: [file]
        always_run: true