repos:
  - repo: local
    hooks:
      - id: sync-shared
        name: Sync shared cookiecutter assets
        entry: poetry run python _scripts/sync_shared.py
        language: system
        types: [file]
        always_run: true